# Generated by Django 4.0.2 on 2022-02-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uruntakip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargoname', models.CharField(blank=True, max_length=200, null=True)),
                ('cargono', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
