# Generated by Django 4.0.2 on 2022-02-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takipapp', '0002_uruntakip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uruntakip',
            name='status',
            field=models.CharField(blank=True, choices=[('Pekin', 'Pekin'), ('Pekin-Ashkabat', 'Pekin-Ashkabat'), ('Ashkabat', 'Ashkabat')], default='Pekin', max_length=200, null=True),
        ),
    ]
